### ISSUE TITLE
Water Drip Sound (waterdripsound) has failed to load correctly

### ISSUE THREAD

**Issue by Ichiriel** [PieKing1215/WaterDripSound#2]
So i've wanted to make a serv with my friend to play at the modpacks: Better Minecraft [FORGE] but on my serv when i try to launch the serv this is appenning : Water Drip Sound (waterdripsound) has failed to load correctly.

here is the crash report:
[crash-2021-07-22_23.08.46-fml.txt](https://github.com/PieKing1215/DripSounds-Forge/files/6865260/crash-2021-07-22_23.08.46-fml.txt)

**Comment by PieKing1215** [comment]
The version of this mod in that crash report is v0.1.3, and the current version is v0.2.1. I'm not sure if there's a reason that modpack is using an old version, but either way v0.1.3 should not be on the server, it is client-side only.
